### ISSUE TITLE
Errors when running the instructions

### ISSUE THREAD

**Issue by shyamalschandra** [SeanNaren/CTCNetworkClient#46] opened 2016-09-04 00:03 UTC
I am getting the following error when running prepare.sh in the prepare_a4 folder of CTC.

```
Shyamals-iMac-174:prepare_an4 shyamalchandra$ sudo ./prepare.sh 
rm: an4_raw.bigendian.tar.gz: No such file or directory
ln: ./Mapper.lua: File exists
ROOT_FOLDER: an4
Converting raw an4 dataset...
Generating Indices...
Generating LMDB...
/Users/shyamalchandra/torch/install/bin/luajit: ...hyamalchandra/torch/install/share/lua/5.1/trepl/init.lua:384: .../shyamalchandra/torch/install/share/lua/5.1/lmdb/ffi.lua:175: dlopen(liblmdb.dylib, 5): image not found
stack traceback:
    [C]: in function 'error'
    ...hyamalchandra/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
    /Users/shyamalchandra/CTCSpeechRecognition/Utils.lua:5: in main chunk
    [C]: in function 'require'
    generateLMDB.lua:1: in main chunk
    [C]: in function 'dofile'
    ...ndra/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x010ce1fcf0
```

What should I do next?

**Comment by SeanNaren** [comment] 2016-09-04 13:57
I assume this is on OSX? I'm not sure how far you can get through the install on OSX but it seems like the issue is with finding lmdb libraries. A quick google came to [this](http://macappstore.org/lmdb/). Maybe this can help!

**Comment by shyamalschandra** [comment] 2016-09-04 17:31
I already have lmdb already installed so there must be some other issue or I should install from source.

**Comment by SeanNaren** [comment] 2016-10-11 10:50
Hey did you manage to fix your issue? I'm not able to help as much because the development environment I have isn't OSX.

**Comment by SeanNaren** [comment] 2016-10-15 16:21
I'll close this for now, if the problem persists we can reopen and try to fix!

**Closed as completed** 2016-10-15 16:21 UTC
